export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
}

export default function About() {
    //throw new Error ("Failed to load data")
    return (
        <div>
            <h1 className="text-3xl font-bold underline">
                about page
            </h1>
        </div>
    )
}