import './globals.css'
import {Montserrat} from "@next/font/google"

const montserrat = Montserrat({
  weight: ["400"],
  subsets: ["latin"],
  variable: '--font-montserrat'
})
export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <nav>
          <h1> Logo </h1>

          <ul>
            <li href="#">
              About
            </li>
            <li>
              <a href="#">
                Sign up
              </a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
